# Exported from Render on 2026-07-26T01:33:21Z
version: "1"
projects:
- name: Luz
  environments:
  - name: Produção
    services:
    - type: web
      name: sabedoria-aprender
      runtime: static
      repo: https://github.com/lz-ntn/sabedoria-coracao
      staticPublishPath: .
      autoDeployTrigger: commit
      rootDir: sites/aprender
    - type: web
      name: sabedoria-viver
      runtime: static
      repo: https://github.com/lz-ntn/sabedoria-coracao
      staticPublishPath: .
      autoDeployTrigger: commit
      rootDir: sites/viver
    - type: web
      name: sabedoria-meditacao
      runtime: static
      repo: https://github.com/lz-ntn/sabedoria-coracao
      staticPublishPath: .
      autoDeployTrigger: commit
      rootDir: sites/meditacao
    - type: web
      name: sabedoria-portal
      runtime: static
      repo: https://github.com/lz-ntn/sabedoria-coracao
      staticPublishPath: .
      autoDeployTrigger: commit
      rootDir: sites/portal
    - type: web
      name: sabedoria-cristianismo
      runtime: static
      repo: https://github.com/lz-ntn/sabedoria-coracao
      staticPublishPath: .
      autoDeployTrigger: commit
      rootDir: sites/cristianismo
    - type: web
      name: sabedoria-curso
      runtime: static
      repo: https://github.com/lz-ntn/sabedoria-coracao
      staticPublishPath: .
      autoDeployTrigger: commit
      rootDir: sites/curso
